import { Inter } from "next/font/google";
import "./globals.css";
import NavLinks from "@/components/NavLinks/NavLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="space-x-4 mx-auto w-max mt-12">
          <NavLinks />
        </div>
        {children}
      </body>
    </html>
  );
}
